# Generated by replygirl/kuru release tooling. Update in the source repository.
class Kuru < Formula
  desc "Persistent equal-part chat harness with isolated memories"
  homepage "https://github.com/replygirl/kuru"
  version "0.11.0"
  license "MIT"

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/replygirl/kuru/releases/download/v0.11.0/kuru-0.11.0-aarch64-apple-darwin.tar.gz"
      sha256 "ab29f24b36a7a77796b64e151ab9351a19b62bb8f6ed0e1829cce03336c12adf"
      resource "shell-support" do
        url "https://github.com/replygirl/kuru/releases/download/v0.11.0/kuru-0.11.0-aarch64-apple-darwin-shell-support.tar.gz"
        sha256 "a0c332b0baf4235d01e267dbc6d2e30f821ff9bb18391e84ba6617f122f161ac"
      end
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/replygirl/kuru/releases/download/v0.11.0/kuru-0.11.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0597cb52e962797cdc8533524dd2e2ba082b9b95383a05877e0644e806ef2637"
      resource "shell-support" do
        url "https://github.com/replygirl/kuru/releases/download/v0.11.0/kuru-0.11.0-aarch64-unknown-linux-gnu-shell-support.tar.gz"
        sha256 "a0c332b0baf4235d01e267dbc6d2e30f821ff9bb18391e84ba6617f122f161ac"
      end
    end
    on_intel do
      url "https://github.com/replygirl/kuru/releases/download/v0.11.0/kuru-0.11.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fd4598c09b70a914a8b12aefa38de5b60d4d2ad3f31e73acac2ded4dc2be4f6f"
      resource "shell-support" do
        url "https://github.com/replygirl/kuru/releases/download/v0.11.0/kuru-0.11.0-x86_64-unknown-linux-gnu-shell-support.tar.gz"
        sha256 "a0c332b0baf4235d01e267dbc6d2e30f821ff9bb18391e84ba6617f122f161ac"
      end
    end
  end

  skip_clean "bin/kuru"
  deny_network_access! [:build, :test]

  def install
    odie "Kuru supports only native Apple Silicon and Linux ARM64/x86-64" unless
      (OS.mac? && Hardware::CPU.arm?) || (OS.linux? && (Hardware::CPU.arm? || Hardware::CPU.intel?))
    bin.install "kuru"
    pkgshare.install "LICENSE", "README.md"
    resource("shell-support").stage do
      bash_completion.install "completions/kuru.bash" => "kuru"
      zsh_completion.install "completions/_kuru"
      fish_completion.install "completions/kuru.fish"
      pwsh_completion.install "completions/kuru.ps1"
      man1.install "man/kuru.1"
    end
  end

  test do
    assert_equal "kuru #{version}\n", shell_output("#{bin}/kuru --version")
    assert_match "NAME", shell_output("#{bin}/kuru man")
    assert_match "kuru", shell_output("#{bin}/kuru completions zsh")
    assert_match "brew upgrade kuru", shell_output("#{bin}/kuru update --version #{version} --release-base https://example.invalid/kuru 2>&1", 1)
  end
end
